### ISSUE TITLE
Load error! when adding content to batch

### ISSUE THREAD

**Issue by jbender0** [concretecms/migration_tool#18]
I'm creating a new batch and after clicking "add content to batch" (and selecting an XML file exported from a C5.6.x site), it scans the content for a few seconds and then shows a "Load error! (Internal Server Error)" message. Here's a screenshot: https://take.ms/VDSzI
The "Errors" tab doesn't show anything. It's not possible to proceed further than this.

Has anyone else run into this error?

Environment info:

Core Version - 9.1.3
Version Installed - 9.1.3
Database Version - 20220908074900

# Environment
production

# Database Information
Version: 10.4.27-MariaDB
SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

# Concrete Packages
Migration Tool (9.0.0)

# Concrete Overrides
None

# Concrete Cache Settings
Block Cache - Off
Overrides Cache - Off
Full Page Caching - Off
Full Page Cache Lifetime - Every 6 hours (default setting).

# Server Software
Apache/2.4.54 (Unix) OpenSSL/1.1.1s PHP/8.1.12 mod_perl/2.0.12 Perl/v5.34.1

# Server API
apache2handler

# PHP Version
8.1.12

# PHP Extensions
apache2handler, bcmath, bz2, calendar, Core, ctype, curl, date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, Phar, posix, Reflection, session, shmop, SimpleXML, soap, sockets, SPL, sqlite3, standard, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib

**Comment by aembler** [comment]
This should be fixed by https://github.com/concretecms/migration_tool/pull/22
