### ISSUE TITLE
Import batch refusing to match block types, attributes, etc.

### ISSUE THREAD

**Issue by jbender0** [concretecms/migration_tool#20]
I've followed the steps in Andrew's video on using the Migration Tool. However, I'm experiencing significant bugs that I've spent hours trying to troubleshoot and making little progress. I've tested on clean Concrete installations running PHP 7.4, 8.0 and 8.1 to check if the PHP version is the cause of the issue, and all have the same results.
I've tested the tool on a small batch - just 1 page with a handful of attributes.
The current hurdle is two-fold:

1) The migration tool appears to not automatically match existing attributes when it actually does. Here's the UI:
https://take.ms/mudwP
https://take.ms/qK9WX
However, what is happening in the database (in the "MigrationContentMapperTargetItems" table) is actually correct. It's matching the "source_item_identifier" correctly.
Then when I choose to "map content", none of those automatic mappings appear. 
Screenshot: https://take.ms/BsWHo
It seems the mappings are correct in the database, but not being loaded (on "map content") or displayed correctly (on "import content", instead a list of warnings and errors). I've tried running the "rescan batch", and although that appears to complete successfully, there's no change in the mappings or warnings/errors.

2) Manual mappings do not save either. Regardless of the automatic mapping not working, when I try the manual option it still does not work. Same as the previous issue - the database records are there in "MigrationContentMapperTargetItems". However, after saving there's no change. So I run "rescan batch" and still there's no change. All the same warnings and errors appear. If I view the "map content" page again, all my previous changes are not displayed.
Since the underlying database seems to be correct, I tried exporting the batch at the end of the process and the page is created (in the correct location), although none of the content or attributes are created. So it's a dud.

I've also tried uninstalling the Migration Tool package and reinstalling with a clean slate (double checking the db tables are no longer there after uninstalling) but makes no difference.

I'm hitting my head against a wall, and have a large website with 1000+ pages to migrate. Please help!

**Comment by jbender0** [comment]
Here's a screencast showing the steps I've followed:
https://monosnap.com/file/ClNrBisPdlk5ZWTJgNbXA4qUNXCBrL

**Comment by aembler** [comment]
This should be fixed by https://github.com/concretecms/migration_tool/pull/22
