### ISSUE TITLE
Broken package

### ISSUE THREAD

**Issue by cgautschi** [concretecms/migration_tool#28]
![Snap2](https://user-images.githubusercontent.com/69804805/215263369-cdf56d5f-ef04-4227-a822-7e4d53ba99d3.jpg)

**Comment by aembler** [comment]
I think you have misnamed the migration tool package folder.

**Comment by cgautschi** [comment]
You're right, thanks.
I forgot to remove the '_-master_' suffix from the folder name in the downloaded ZIP file.

**Comment by aembler** [comment]
No worries, glad to hear that helped.
